# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OpenRide' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  # use_frameworks!

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end
    end
  end

  pod 'Bugsnag'

  target 'OpenRideTests' do
    
    #inherit! :search_paths
    # Pods for testing
  end

end


